name: Create Azure Resource Group

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

env:
  #DEV_RESOURCE_GROUP_NAME: rg-dlyog-dev
  ENVIRONMENT_TYPE: dev
  AZ_LOCATION: westus

jobs:
  create-resource-group-for-dev-environment:
    runs-on: [self-hosted,Linux,X64,openid]
    environment: terraform-dev1-plan-apply
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: 'Code checkout'
        uses: actions/checkout@v2
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: check current directory
        id: basic_cli_command
        run: |
          pwd
          ls
          echo "DEV_RESOURCE_GROUP_NAME=rg-$((RANDOM))" >> $GITHUB_ENV
        # echo $ACTIONS_ID_TOKEN_REQUEST_URL
        #echo $ACTIONS_RUNTIME_TOKEN
      
      - name: Create development resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.31.0
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az group create --location ${{ env.AZ_LOCATION }} --name ${{ env.DEV_RESOURCE_GROUP_NAME }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --tags environment=${{ env.ENVIRONMENT_TYPE }}
      
      - name: check if Resource Group Created Success Fully
        uses: azure/CLI@v1
        with:
          azcliversion: 2.31.0
          inlineScript: |
            az group show --name ${{ env.DEV_RESOURCE_GROUP_NAME }}