name: create_aks_cluster

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

env:
  #DEV_RESOURCE_GROUP_NAME: rg-dlyog-dev
  ENVIRONMENT_TYPE: dev
  AZ_LOCATION: westus

jobs:
  create-resource-group-for-dev-environment:
    runs-on: [self-hosted,Linux,X64,openid]
    environment: terraform-dev1-plan-apply
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        shell: bash
        working-directory: ./github-action-oidc-demo

    steps:
      - name: 'Code checkout'
        uses: actions/checkout@v2
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
      - name: check current directory
        id: basic_cli_command
        run: |
          pwd
          ls
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="path=${{ secrets.TF_STATE_SELF_HOSTED_PATH }}/terraform.tfstate"
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Apply
        run: terraform apply --auto-approve